version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic

  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

  exclusions:
    paths:
      - .private
      - .private-config

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
